import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { agentManifestSchema, type AgentManifest } from "../schemas/agent-manifest.js";

type RouteDefinition = AgentManifest["routes"][number];

export type GeneratedFile = {
  type: "routes";
  path: string;
  count: number;
};

type AgentManifestInput = {
  agent: string;
  manifestPath?: string;
};

export async function generateRoutesFile(workspacePath: string, agents: AgentManifestInput[]): Promise<GeneratedFile | undefined> {
  const manifests = await loadAcceptedManifests(agents);
  const routes = manifests
    .flatMap((manifest) => manifest.routes)
    .sort(compareRoutes);

  if (routes.length === 0) {
    return undefined;
  }

  const outputPath = "src/generated/routes.ts";
  const fullOutputPath = join(workspacePath, outputPath);
  await mkdir(dirname(fullOutputPath), { recursive: true });
  await writeFile(fullOutputPath, renderRoutes(routes));

  return {
    type: "routes",
    path: outputPath,
    count: routes.length,
  };
}

async function loadAcceptedManifests(agents: AgentManifestInput[]): Promise<AgentManifest[]> {
  const manifests: AgentManifest[] = [];

  for (const agent of agents) {
    if (!agent.manifestPath) {
      continue;
    }

    const parsed = agentManifestSchema.parse(JSON.parse(await readFile(agent.manifestPath, "utf8")));
    manifests.push(parsed);
  }

  return manifests;
}

function renderRoutes(routes: RouteDefinition[]): string {
  return `// AUTO-GENERATED BY AgentX.
// DO NOT EDIT BY HAND.
// Source: accepted agent-output/manifest.json files.

export const routes = ${JSON.stringify(routes, null, 2)} as const;
`;
}

function compareRoutes(left: RouteDefinition, right: RouteDefinition): number {
  return (left.priority ?? 100) - (right.priority ?? 100) || left.path.localeCompare(right.path) || left.id.localeCompare(right.id);
}
