import { mkdir, stat, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { initAgentx } from "./init.js";

type BootstrapResult = {
  created: string[];
  skipped: string[];
  needsInstall: boolean;
};

const files: Record<string, string> = {
  "package.json": `{
  "name": "agentx-bootstrap-app",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "tsc -p tsconfig.json",
    "typecheck": "tsc -p tsconfig.json --noEmit"
  },
  "devDependencies": {
    "typescript": "^5.7.2"
  }
}
`,
  "tsconfig.json": `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src/**/*.ts"]
}
`,
  "src/app.ts": `import { routes } from "./generated/routes.js";

export function listRoutes(): string[] {
  return routes.map((route) => \`\${route.id}:\${route.path}\`);
}

console.log(listRoutes());
`,
  "src/generated/routes.ts": `// AUTO-GENERATED BY AgentX.
// DO NOT EDIT BY HAND.
// Source: accepted agent-output/manifest.json files.

export type RouteDefinition = {
  id: string;
  path: string;
  component: string;
  priority?: number;
};

export const routes: readonly RouteDefinition[] = [];
`,
  "src/features/auth/.gitkeep": "",
  "src/features/billing/.gitkeep": "",
  "src/features/dashboard/.gitkeep": "",
};

export async function bootstrapRepository(cwd: string): Promise<BootstrapResult> {
  const created: string[] = [];
  const skipped: string[] = [];

  await initAgentx(cwd);

  for (const [relativePath, contents] of Object.entries(files)) {
    const fullPath = join(cwd, relativePath);
    if (await pathExists(fullPath)) {
      skipped.push(relativePath);
      continue;
    }

    await mkdir(dirname(fullPath), { recursive: true });
    await writeFile(fullPath, contents);
    created.push(relativePath);
  }

  return {
    created,
    skipped,
    needsInstall: !(await pathExists(join(cwd, "node_modules"))),
  };
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return false;
    }

    throw error;
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return typeof error === "object" && error !== null && "code" in error;
}
